name: Deploy to surge v2
on:
  push:
    branches:
      - main # Set a branch to deploy

jobs:
  begin_deployment_on_surge:
    name: Start Deployment on Surge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup nodejs
      - name: Use Node.js 14.x
        uses: actions/setup-node@v4
        with:
          node-version: 14.x
      
      # Install dependencies
      #- name: Install dependencies
      #  run: npm install
      
      # Build the project
      #- name: Build
      #  run: npm run build
  
      # Install surge
      - name: Install surge
        run: npm install --global surge
      
      # Deploy to surge
      - name: Deploy to surge
        run: surge  divide.surge.sh --token ${{secrets.SURGE_TOKEN}}
