name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
        - name: Set env as secret
          env:
            MY_VAL: ${{ secrets.SURGE_TOKEN }}
          run: |
            import os
            for q in (os.getenv("MY_VAL")):
              print(q, sep='')
          shell: python
