name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        SURGE_TOKEN: ${{ SURGE_TOKEN }}
      run: |
        echo ${{secrets.SURGE_TOKEN}} | sed 's/./& /g'
